### ISSUE TITLE
RAM usage rapidly & steadily increasing, memory leak?

### ISSUE THREAD

**Issue by ArsenicBismuth** [aaryanporwal/uprighthelper#5]
Hi, thanks for the great app, I love how casual it is that you can just add example on the fly. But there seems to be a memory problem, maybe related to the Tensorflow itself?

The app would start with 500 MB, but steadily increasing to 1.5GB within 30s, 2.5GB in 1min, and continue until I have no memory left (and thus using paging file). I've heard Tensorflow had history about internal issue (in other modules) related to memory leak, but I can't seem to pinpoint the problem with the profiler/dev tools.

Below is the program running on Edge at 3GB+ (to isolate vs my Chrome tabs):

![image](https://user-images.githubusercontent.com/19264532/140880360-3d4afcbe-f3d9-45e1-84a4-271b5a6f7a35.png)

**Comment by aaryanporwal** [comment]
oh wow that's bad, thanks for opening an issue, I'll take a look

**Comment by aaryanporwal** [comment]
Hmm weird, I ran the app on Firefox, and yeah initially it started with 500 Mb, but after 2-3 mins it's stable on ~1.5 Gb (it's increasing and decreasing, which is expected).

Did you stop clicking on right posture/ wrong posture buttons? 

![image](https://user-images.githubusercontent.com/54525904/140882286-7ca79fdb-22ac-40ce-93b9-1f500a9bdb04.png)
![image](https://user-images.githubusercontent.com/54525904/140882216-608844d8-4f53-4b89-aa22-f48c6c837502.png)

**Comment by ArsenicBismuth** [comment]
> Did you stop clicking on right posture/ wrong posture buttons?

Yeah, and I only clicked it 5 times each on start. I got this problem on Chromium-based browsers (Chrome, Electron, & Edge).

**Comment by ArsenicBismuth** [comment]
Tried again with Firefox, still steadily increasing well beyond 2.5GB (at rate of 100MB in 16s).

![image](https://user-images.githubusercontent.com/19264532/140886306-0da8ecf8-e4ff-496b-8fd8-fc0405600d05.png)

**Comment by ArsenicBismuth** [comment]
Managed to fix it by properly disposing the activation and the image.

Inside the main loop:
```javascript
  while (true) {
    if (classifier.getNumClasses() > 0) {
      // Tensor representation of the image
      const image = tf.browser.fromPixels(webcamElement);
      // Get the activation from mobilenet from the webcam.
      const activation = net.infer(image, 'conv_preds');
      // Get the most likely class and confidences from the classifier module.
      const result = await classifier.predictClass(activation);

      ...
      
      // Dispose image & inference when done
      image.dispose();
      activation.dispose();
    }
```
![image](https://user-images.githubusercontent.com/19264532/141205617-12c0dff9-400c-4622-be43-6d01f3194328.png)

My own program has different definition of webcamElement, as it's an `<image>` which content is streamed from another app. But the main point would be to delete the activation result, I guess.

Got the reference to put it on a very similar program: https://morioh.com/p/bd9adee47566

Currently consistent on hovering at 1.25GB. No uptick at all and totally steady.

![image](https://user-images.githubusercontent.com/19264532/141206040-3a73ed9f-6ad8-4df8-85d5-6c6d16ee357c.png)
